name = "nft-staking"
gas_price = '0.025ueaura'
gas_adjustment = 1.3
account_prefix = 'aura'
derivation_path = '''m/44'/118'/0'/0/0'''

[wasm]
contract_dir = 'contracts'
optimizer_version = '0.12.11'

[networks.serenity]
chain_id = 'serenity-testnet-001'
network_variant = 'Shared'
grpc_endpoint = 'https://grpc.serenity.aura.network:9092'
rpc_endpoint = 'https://rpc.serenity.aura.network'

[networks.euphoria]
chain_id = 'euphoria-2'
network_variant = 'Shared'
grpc_endpoint = 'http://grpc.euphoria.aura.network:9090'
rpc_endpoint = 'https://rpc.euphoria.aura.network'


[accounts.signer]
mnemonic = 'meat hazard ivory idle grass chronic menu series alien build spoon arch organ tornado joy year earth broken brain eagle special ticket canal boy'
